# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-24 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ans',
            name='excludes',
        ),
    ]
