# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-21 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qanswer', '0002_auto_20171122_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
