# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-21 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qanswer', '0005_question_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
