# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-22 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import qanswer.validators


class Migration(migrations.Migration):

    dependencies = [
        ('qanswer', '0007_question_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[qanswer.validators.validate_category]),
        ),
    ]
